# -*- coding: utf-8 -*-
"""AI-day1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NuRKHqXXHWSO8_rJDJs9Q09rhvhbA276
"""

graph = {
    'A':['B', 'C'],
    'B':['A','D','E'],
    'C':['A','F'],
    'D':['B'],
    'E':['B'],
    'F':['C']

}

def dfs(graph, node, visited=None):
  if visited is None:
    visited = set()

  print(node)

  for neighbour in graph[node]:
    if neighbour not in visited:
      dfs(graph, neighbour, visited)


print("Depth first search traversal starting from node A:")
dfs(graph, 'A')

